name: ✨ Feature Request
description: Suggest a new idea for the template.
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - Mela13076

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      placeholder: What would you like to see added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this important?
      placeholder: Explain the need or problem it solves.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add additional context here. For screenshots, drag-and-drop them **after** submitting the issue.
      placeholder: Add notes if helpful.
